Repair Find CodeSystem by ValueSet logic
FirelyTeam/Firely.Fhir.Packages pull request #36
Opened 2022-07-20 14:21 UTC by mmsmits

2022-07-21 09:51 UTC, marcovisserFurore requested changes
I missing a unit test for this change.

2022-07-21 09:51 UTC, marcovisserFurore commented on Firely.Fhir.Packages.props
>          <VersionSuffix></VersionSuffix>
This should be alpha as well

2022-07-21 11:28 UTC, mmsmits commented
> I missing a unit test for this change.

@marcovisserFurore The unit test was already there, and didn't need change:
https://github.com/FirelyTeam/Firely.Fhir.Packages/blob/415b78081a36051de5122413d36681bd931b63db/Firely.Fhir.Packages.Tests/ResolveTests.cs#L23

2022-07-28 11:43 UTC, marcovisserFurore approved these changes

2022-07-28 11:43 UTC, merged